### ISSUE TITLE
NAOMI Icons suggestion

### ISSUE THREAD

**Issue by vin564** [Vidnez/retro-systems-icons-for-GarlicOS#2]
Greetings, I (crudely) made these NAOMI icons. They aren't perfect, but as there wasn't any on the repo, I tried to make them myself. If you want to add them or get inspired to make your own version, you're welcome! (Although, in my opinion, they look pretty good)

![NAOMI](https://github.com/Vidnez/retro-systems-icons-for-GarlicOS/assets/115725477/fefcfa4f-a2bb-498a-9dec-4568feea0507)
![NAOMI_ALT](https://github.com/Vidnez/retro-systems-icons-for-GarlicOS/assets/115725477/eb38ab1f-ecfa-48bb-9930-071ac43d74bf)

**Comment by Vidnez** [comment]
They are great, but the console needs to have a pixelated look. If you don't mind I'll use this version:
![Naomi](https://github.com/Vidnez/retro-systems-icons-for-GarlicOS/assets/82564218/2d6e8f17-5397-4503-b58b-65fbf628397f)

**Comment by vin564** [comment]
Great! That image is indeed more adequate to the artstyle, I should have searched a little bit more for a front-facing image, greatly appreciate that you took the time to make a new icon.

One little thing though, wasn't the board released in 1998, according to, for example, this: https://segaretro.org/Sega_NAOMI ?

And also, while i'm at it, I wonder, would you be willing to also submit another template (maybe on a .psd format), containing that year box and some text placeholders for the best accuracy when making custom icons?
