### ISSUE TITLE
No Saturn?

### ISSUE THREAD

**Issue by cehenriques** [Vidnez/retro-systems-icons-for-GarlicOS#4]
Hi.

Am I looking wrong, or there is no icon for Sega Saturn?

Thanks! Great work!

**Comment by Vidnez** [comment]
There is no Saturn icon because GarlicOS is not compatible with that system. But here's one:

![saturn](https://github.com/user-attachments/assets/47541b56-20ed-4e3b-80df-b4cbbde93546)

**Comment by cehenriques** [comment]
> There is no Saturn icon because GarlicOS is not compatible with that system. But here's one:
> 
> ![saturn](https://private-user-images.githubusercontent.com/82564218/350744484-47541b56-20ed-4e3b-80df-b4cbbde93546.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1NDg4MjMsIm5iZiI6MTcyMTU0ODUyMywicGF0aCI6Ii84MjU2NDIxOC8zNTA3NDQ0ODQtNDc1NDFiNTYtMjBlZC00ZTNiLTgwZGYtYjRjYmJkZTkzNTQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIxVDA3NTUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkMmEzNjY1MDVkNThhZTNiY2I0YzBkOTdhNTY5NjM5N2EyZGFmNTkxNjBmYjA2OTU1YjU3NDE4MWU3OTJiMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0UKUibSbZBr4h_D_K-cjdnUqJSpDQuNvbQPevMuqUm0)

Thank you!!!
